import { today, money, summarize, validatePlan } from './logic.js';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export const report={mode:'month',year:Number(today().slice(0,4)),period:Number(today().slice(5,7))};
export function analytics(payments){
 const s=summarize(payments,report.mode,report.year,report.period),max=Math.max(1,...s.buckets.map(b=>b.total));
 const periodLabel=report.mode==='year'?`Năm ${report.year}`:report.mode==='quarter'?`Quý ${report.period}/${report.year}`:`Tháng ${report.period}/${report.year}`;
 return `<section class="panel analytics"><div class="panel-head"><div><h2>Kết quả thu phí</h2><small>${periodLabel} · Theo ngày thực thu, không phải công nợ</small></div><div class="report-controls"><label>Xem theo<select id="report-mode"><option value="month" ${report.mode==='month'?'selected':''}>Tháng</option><option value="quarter" ${report.mode==='quarter'?'selected':''}>Quý</option><option value="year" ${report.mode==='year'?'selected':''}>Năm</option></select></label><label>Năm<input id="report-year" type="number" min="2000" max="2100" value="${report.year}"></label>${report.mode!=='year'?`<label>${report.mode==='quarter'?'Quý':'Tháng'}<select id="report-period">${Array.from({length:report.mode==='quarter'?4:12},(_,i)=>`<option value="${i+1}" ${report.period===i+1?'selected':''}>${i+1}</option>`).join('')}</select></label>`:''}</div></div><div class="finance-stats"><article><span>Tiền thực thu</span><strong>${money(s.total)}</strong><small>${s.receipts} khoản thu đã ghi nhận</small></article><article><span>Hội viên đăng ký mới</span><strong>${s.newMembers}</strong><small>Đếm hội viên có khoản đăng ký đầu tiên</small></article><article><span>Lượt gia hạn</span><strong>${s.renewals}</strong><small>Mỗi lần thu gia hạn là một lượt</small></article></div><div class="report-breakdown"><h3>Chi tiết từng tháng</h3><p class="helper">Giữ lại số liệu khi xóa hồ sơ hội viên. Không suy ra tiền thu từ giá gói.</p><div class="report-table-wrap"><table class="report-table"><thead><tr><th>Tháng</th><th>Đăng ký mới</th><th>Gia hạn</th><th>Tiền thực thu (đ)</th></tr></thead><tbody>${s.buckets.map(b=>`<tr><th scope="row">${b.month.slice(5)}/${b.month.slice(0,4)}</th><td>${b.newMembers}</td><td>${b.renewals}</td><td><strong>${money(b.total)}</strong><div class="revenue-track" aria-hidden="true"><span style="width:${Math.round(b.total/max*100)}%"></span></div></td></tr>`).join('')}</tbody></table></div>${!s.receipts?'<p class="helper">Chưa có khoản thu trong kỳ đã chọn.</p>':''}</div></section>`;
}
export function changeReport(el){if(el.id==='report-mode'){report.mode=el.value;report.period=report.mode==='quarter'?Math.ceil(Number(today().slice(5,7))/3):Number(today().slice(5,7));return true;}if(el.id==='report-year'){const n=Number(el.value);if(!Number.isInteger(n)||n<2000||n>2100){el.setCustomValidity('Năm phải từ 2000 đến 2100.');el.reportValidity();return false;}el.setCustomValidity('');report.year=n;return true;}if(el.id==='report-period'){report.period=Number(el.value);return true;}return false;}
export function packageView(plans){return `<section class="panel"><div class="panel-head"><div><h2>Danh mục gói tập</h2><small>Giá niêm yết theo đồng · Khi thu tiền có thể nhập số thực nhận khác</small></div><button class="primary" data-action="add-plan">Thêm gói tập</button></div><div class="package-grid">${[...plans].sort((a,b)=>a.months-b.months).map(p=>`<article class="package-card ${!p.active?'disabled-plan':''}"><span class="eyebrow">${p.months} THÁNG LỊCH</span><h3>${esc(p.name)}</h3><strong class="package-price">${money(p.price)}</strong><p class="helper">${p.active?'Đang mở đăng ký':'Đã ngừng mở đăng ký'}</p><button data-action="edit-plan" data-id="${esc(p.id)}">Sửa gói / trạng thái</button></article>`).join('')}</div><div class="inline-note">Ngừng gói thay vì xóa: không làm mất thông tin gói và lịch sử của hội viên cũ. Cuối tháng được tính tới ngày hợp lệ gần nhất.</div></section>`;}
export function planOptions(plans,selected='',legacy=false){return `${legacy?`<option value="" ${!selected?'selected':''}>Giữ gói hiện tại (hồ sơ cũ)</option>`:''}${plans.filter(p=>p.active||p.id===selected).map(p=>`<option value="${esc(p.id)}" ${p.id===selected?'selected':''}>${esc(p.name)} · ${money(p.price)}${!p.active?' · đã ngừng':''}</option>`).join('')}`;}
export function packageFields(plan){return plan?{planId:plan.id,planName:plan.name,planMonths:plan.months,monthlyFee:plan.price}:{};}
export function planFormMarkup(p,head){return `${head(p?'Sửa gói tập':'Thêm gói tập')}<form id="plan-form" class="modal-body"><div class="form-grid"><label class="span-2">Tên gói *<input name="name" minlength="2" maxlength="80" required value="${esc(p?.name||'')}"></label><label>Thời lượng (tháng) *<input name="months" type="number" min="1" max="24" step="1" required value="${p?.months||1}"></label><label>Giá niêm yết (đ) *<input name="price" type="number" min="1" max="100000000" step="1" required value="${p?.price||250000}"></label><label class="span-2">Trạng thái<select name="active"><option value="true" ${p?.active!==false?'selected':''}>Đang mở đăng ký</option><option value="false" ${p?.active===false?'selected':''}>Ngừng mở đăng ký</option></select></label></div><p id="form-error" class="error" role="alert"></p><div class="modal-actions"><button type="button" data-action="close">Hủy</button><button type="submit" class="primary">Lưu gói tập</button></div></form>`;}
export function cleanPlan(form){const fields=Object.fromEntries(new FormData(form));return validatePlan({...fields,active:fields.active==='true'});}
export function photoMarkup(){return `<div class="photo-editor span-2"><div class="photo-preview" id="photo-preview">Chưa có ảnh</div><div><strong>Ảnh hội viên</strong><div class="photo-buttons"><button type="button" id="choose-photo">Chọn ảnh</button><button type="button" id="take-photo">Chụp ảnh</button><button type="button" id="clear-photo">Bỏ ảnh</button></div><input id="photo-file" type="file" accept="image/jpeg,image/png,image/webp" hidden><input id="photo-camera" type="file" accept="image/*" capture="environment" hidden><p class="helper">Ảnh JPG/PNG/WebP tối đa 5 MB; tự thu nhỏ trước khi lưu. Chụp ảnh phụ thuộc trình duyệt điện thoại; máy tính có thể mở hộp chọn tệp.</p><p id="photo-error" class="error" role="alert"></p></div></div>`;}
export function attachPhoto(form,member,store,resolveUrl){
 let blob=null,path=member?.photoPath||'',avatar=member?.avatar||'',removed=false,previewUrl='',busy=false,version=0,disposed=false;
 const preview=form.querySelector('#photo-preview'),error=form.querySelector('#photo-error');
 function revoke(){if(previewUrl){URL.revokeObjectURL(previewUrl);previewUrl='';}}
 function show(url){preview.replaceChildren();if(url){const img=new Image();img.src=url;img.alt='Ảnh hội viên xem trước';img.onerror=()=>{preview.textContent='Không tải được ảnh';};preview.append(img);}else preview.textContent='Chưa có ảnh';}
 if(path)resolveUrl(path).then(url=>{if(!removed&&!blob&&!disposed)show(url);}).catch(()=>{if(!disposed)preview.textContent='Không tải được ảnh cũ';});else show(avatar);
 async function choose(file){if(!file)return;const ticket=++version;busy=true;error.textContent='Đang xử lý ảnh…';try{if(file.size>5*1024*1024)throw new Error('Ảnh vượt 5 MB. Vui lòng chọn ảnh nhỏ hơn.');if(!['image/jpeg','image/png','image/webp'].includes(file.type))throw new Error('Chọn ảnh JPG, PNG hoặc WebP; ảnh HEIC cần đổi sang JPG.');const source=URL.createObjectURL(file);let img;try{img=await new Promise((resolve,reject)=>{const image=new Image();image.onload=()=>resolve(image);image.onerror=()=>reject(new Error('Không đọc được ảnh. Hãy chọn ảnh khác.'));image.src=source;});}finally{URL.revokeObjectURL(source);}const scale=Math.min(1,800/Math.max(img.naturalWidth,img.naturalHeight));const canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(img.naturalWidth*scale));canvas.height=Math.max(1,Math.round(img.naturalHeight*scale));const ctx=canvas.getContext('2d');ctx.fillStyle='#fff';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.drawImage(img,0,0,canvas.width,canvas.height);const next=await new Promise(resolve=>canvas.toBlob(resolve,'image/jpeg',.82));if(!next||next.size>1048576)throw new Error('Ảnh sau xử lý vẫn quá lớn. Hãy chọn ảnh khác.');if(ticket!==version||disposed)return;blob=next;path='';avatar='';removed=false;revoke();previewUrl=URL.createObjectURL(blob);show(previewUrl);error.textContent='';}catch(e){if(ticket===version&&!disposed)error.textContent=e.message;}finally{if(ticket===version)busy=false;}}
 form.querySelector('#choose-photo').onclick=()=>form.querySelector('#photo-file').click();form.querySelector('#take-photo').onclick=()=>form.querySelector('#photo-camera').click();
 for(const id of ['photo-file','photo-camera'])form.querySelector('#'+id).onchange=e=>choose(e.target.files[0]);
 form.querySelector('#clear-photo').onclick=()=>{version++;busy=false;blob=null;path='';avatar='';removed=true;revoke();show('');error.textContent='';for(const id of ['photo-file','photo-camera'])form.querySelector('#'+id).value='';};
 return {dirty:()=>removed||!!blob,dispose:()=>{disposed=true;version++;revoke();},save:async()=>{if(busy)throw new Error('Ảnh đang xử lý. Hãy chờ rồi lưu lại.');if(blob&&!path)path=await store.uploadPhoto(blob);return {avatar,photoPath:path};}};
}
